export const CONNECT_SUCCESS = 'CONNECT_SUCCESS';
export const CONNECT_FAIL = 'CONNECT_FAIL';

export const NEW_MESSAGES_RECEIVED = 'NEW_MESSAGES_RECEIVED';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_TEXT_CHANGED = 'MESSAGE_TEXT_CHANGED';
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS';

export const ROOM_FORM_NAME_CHANGED = 'ROOM_FORM_NAME_CHANGED';
export const ROOM_CREATE_SUCCESS = 'ROOM_CREATE_SUCCESS';

export const NEW_ROOMS_LIST_RECEIVED = 'NEW_ROOMS_LIST_RECEIVED';

export const USERNAME_CHANGED = 'USERNAME_CHANGED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
